#cloud-config
autoinstall:
  version: 1
  locale: pt_BR
  timezone: America/Manaus
  storage:
    layout:
      - name: root
        use: entire
        wipe: true

  packages:
    - ubuntu-desktop
    - openssh-server
    - build-essential
    - curl
    - git
    - vim
    - emacs
    - gnome-tweaks
    - wget 
    - gstreamer1.0-plugins-base # Plugins básicos do GStreamer
    - gstreamer1.0-plugins-good # Plugins adicionais úteis
    - gstreamer1.0-plugins-bad # Plugins menos testados, mas podem ser úteis
    - gstreamer1.0-plugins-ugly # Plugins com problemas de licenciamento, use com cuidado
    - gstreamer1.0-libav # Plugin para suporte a formatos de áudio/vídeo populares
    - gstreamer1.0-tools # Ferramentas de linha de comando do GStreamer

  # Habilitar o usuário root com senha vazia (NÃO RECOMENDADO PARA PRODUÇÃO)
  users:
    - name: root
      pass: '$6$aqP6n/H1KQ6gR9gR$x22skbobxY5R06FKZ2yU7.pQ8i03WHJoj8y92DA26MmRun2.bI/Xjnu1x5p1YlQ14K.tT2sqa98w0i2160'  # Hash da senha vazia
      sudo: ALL=(ALL) ALL

  late-commands:
    - curtin in-target -- bash -c '
        # Instalar Miniconda e Mamba
        curl -sSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/miniconda.sh &&
        bash ~/miniconda.sh -b -p /opt/miniconda &&
        rm ~/miniconda.sh &&
        echo "PATH=/opt/miniconda/bin:$PATH" >> /etc/environment &&
        /opt/miniconda/bin/conda install -y mamba &&
        /opt/miniconda/bin/conda config --set auto_activate_base false &&
        echo "conda activate" >> /root/.bashrc &&

        # Instalar pacotes Python comuns (opcional)
        /opt/miniconda/bin/mamba create -y -n dev python=3.10 numpy scipy matplotlib pandas jupyterlab &&

        # Instalar outras ferramentas de desenvolvimento (opcional)
        apt-get update &&
        apt-get install -y docker.io docker-compose nodejs npm

        # Instalar VMware Workstation Pro
        wget -q https://www.vmware.com/go/getworkstation-linux --no-check-certificate -O ~/vmware.bin &&
        chmod +x ~/vmware.bin &&
        bash ~/vmware.bin &&
        rm ~/vmware.bin &&

        # Instalar IntelliJ IDEA
        snap install intellij-idea-community --classic &&

        # Instalar GitKraken
        wget -q https://release.axocdn.com/linux/GitKraken-v8.7.0.deb --no-check-certificate -O ~/gitkraken.deb &&
        dpkg -i ~/gitkraken.deb &&
        rm ~/gitkraken.deb &&

        # Instalar Microsoft Teams
        curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&
        sh -c "echo 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main' > /etc/apt/sources.list.d/teams.list" &&
        apt-get update &&
        apt-get install -y teams &&

        # Instalar Skype
        snap install skype --classic &&

        # Instalar OneDrive
        wget -q https://github.com/abraunegg/onedrive/releases/download/v2.4.22/onedrive_2.4.22-1_amd64.deb --no-check-certificate -O ~/onedrive.deb &&
        dpkg -i ~/onedrive.deb &&
        rm ~/onedrive.deb &&

        # Instalar Android Studio
        snap install android-studio --classic &&

        # Instalar Obsidian
        snap install obsidian &&

        # Instalar Discord
        snap install discord 
      '
